# Generated by Django 3.1.5 on 2021-01-31 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=6, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.CharField(max_length=500)),
                ('course_learnings', models.CharField(max_length=500)),
                ('topics_covered', models.CharField(max_length=500)),
                ('course_prerequisites', models.CharField(max_length=500)),
                ('course_prep_required', models.CharField(max_length=500)),
                ('course_pdu', models.CharField(max_length=500)),
                ('course_seu', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='test', max_length=200)),
                ('event_id', models.CharField(max_length=6, unique=True)),
                ('event_date_time', models.DateTimeField()),
                ('event_format', models.CharField(choices=[('CL', 'Classroom'), ('OL', 'Online')], max_length=2)),
                ('event_who_will_benefit', models.CharField(max_length=500)),
                ('event_what_will_you_learn', models.CharField(max_length=500)),
                ('event_What_you_will_get', models.CharField(max_length=500)),
                ('event_refund_policy', models.CharField(max_length=500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.course')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fname', models.CharField(default='test', max_length=100)),
                ('registration_lname', models.CharField(default='test', max_length=100)),
                ('registration_email', models.EmailField(default='test', max_length=200)),
                ('registration_contact_number', models.CharField(max_length=20)),
                ('registration_unique_id', models.CharField(max_length=15)),
                ('registration_coupon_code', models.CharField(max_length=200)),
                ('registration_paid_status', models.BooleanField()),
                ('registration_paid_amount', models.CharField(max_length=200)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.event')),
            ],
        ),
    ]
