# Generated by Django 3.1.5 on 2021-01-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
    ]
